apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-storage
  namespace: document-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi